language: python

python:
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran

install: pip install -r requirements-testing.txt -e .

script: py.test
